- name: Remove existing directory
  ansible.builtin.file:
    path: "./cfgmdir"
    state: absent

- name: Clone GitHub repository
  git:
    repo: "{{ github_repo }}"
    dest: "./cfgmdir"  # Clones into the current directory
    clone: yes
    update: yes

- name: Build Docker Image
  ansible.builtin.command:
    cmd: docker build -t {{container_name}} .
  args:
    chdir: ./cfgmdir/reactjsapp  # Specify the directory of your Dockerfile if not in home directory
  become: false  # Run as the current user

- name: Run Docker Container
  ansible.builtin.command:
    cmd: docker run -d -p 3000:3000 {{container_name}}
  become: false  # Run as the current user
  register: docker_run_output

- name: Show output of Docker run command
  ansible.builtin.debug:
    var: docker_run_output.stdout_lines

- name: Reload Apache to apply changes
  ansible.builtin.service:
    name: httpd
    state: restarted
  become: true # Run as root