- name: Install git, yum-utils, device-mapper-persistent-data, and lvm2
  ansible.builtin.yum:
    name:
      - git
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - docker
      - httpd
    state: present
    update_cache: true

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Start and enable Apache service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: Ensure the current user is in the docker group
  ansible.builtin.user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes
  become: true

- name: Add VirtualHost configuration to httpd.conf
  ansible.builtin.blockinfile:
    path: /etc/httpd/conf/httpd.conf
    block: |
      <VirtualHost *:80>
          ServerName {{subdomain_name}}.{{ domain_name }}
          ServerAlias www.{{subdomain_name}}.{{ domain_name }}
          ProxyPreserveHost On
          ProxyPass / http://localhost:3000/
          ProxyPassReverse / http://localhost:3000/
      </VirtualHost>
    marker: "# {mark} ANSIBLE MANAGED BLOCK for demo.{{ domain_name }}"
    create: yes
    backup: yes
  become: true # Run as root

- name: Reload Apache to apply changes
  ansible.builtin.service:
    name: httpd
    state: restarted
  become: true # Run as root

